language: java
script: mvn package
notifications:
  email: never
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: "./target/xci-splitter-*-win64.jar"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true