language: java
script: mvn package
notifications:
  email: never
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: 
    - "./releases/win64/target/xci-splitter-*.jar"
    - "./releases/linux64/target/xci-splitter-*.jar"
    - "./releases/osx/target/xci-splitter-*-capsule.jar"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true